serverAddr = "54.169.95.15"
serverPort = 7000


[[proxies]]
name = "kcp-udp"
type = "udp"
localIP = "127.0.0.1"
localPort = 45000
remotePort = 45000

[[proxies]]
name = "kcp-tcp"
type = "tcp"
localIP = "127.0.0.1"
localPort = 45000
remotePort = 45000

[[proxies]]
name = "tcp-http"
type = "tcp"
localIP = "127.0.0.1"
localPort = 44444
remotePort = 44444
